channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
      - pandas
      - numpy
      - seaborn
      - joblib
      - scikit-learn==0.23.2
      - lightgbm
      - azureml-mlflow
      name: azureml_workshop
