channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - pandas
      - numpy
      - seaborn
      - joblib
      - lightgbm
      - scikit-learn
      - azureml-mlflow
name: azureml_workshop